# Generated by Django 4.0.4 on 2022-05-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_informationplant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationPlant',
        ),
        migrations.DeleteModel(
            name='StatusLedRed',
        ),
        migrations.RenameField(
            model_name='controlboard',
            old_name='Mode',
            new_name='hex',
        ),
        migrations.RemoveField(
            model_name='controlboard',
            name='Plant',
        ),
        migrations.AddField(
            model_name='controlboard',
            name='b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controlboard',
            name='g',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controlboard',
            name='r',
            field=models.IntegerField(default=0),
        ),
    ]
